### ISSUE TITLE
[BUG] [POPS] [Soph] UI issue icon not shown in the add liquidity page

### ISSUE THREAD

**Issue by sophoah** [harmony-one/swoop-testing#15]
**Site/Domain**
swoop.pops.one

**Describe the bug**
token icon not shown

**To Reproduce**
create the corresponding liquidity pair

**Expected behavior**
token icon shown

**Screenshots**
![image](https://user-images.githubusercontent.com/35721420/97085866-a8cbf400-1652-11eb-991a-c88455092ef2.png)
![image](https://user-images.githubusercontent.com/35721420/97088587-788d5100-1664-11eb-85bf-65ab2432eac0.png)

**Additional context**

**Comment by hypnagonia** [comment]
double for https://github.com/harmony-one/swoop-testing/issues/8
