### ISSUE TITLE
[BUG] [POPS] [Soph] Adding new liquidity with higher amount than previous doesn't ask for approval

### ISSUE THREAD

**Issue by sophoah** [harmony-one/swoop-testing#16]
**Site/Domain**

https://swoop.pops.one

**Describe the bug**

I was adding liquidity for 1BUSD/1BTC (a second time after I removed completely previously). The first time I added the liquidity that was for (1000/1000). I removed it with at 1050/950, then now trying to add back now 1102.34/1000

**To Reproduce**

See describe bug

**Expected behavior**

It should ask for approval I think, I am not 100% sure here on the approval requirement

**Screenshots**

the screenshot was taken after was after I clicked on "confirm supply" :
![image](https://user-images.githubusercontent.com/35721420/97088940-d1f67f80-1666-11eb-8b1b-d80a56968686.png)

**Additional context**

**Comment by hypnagonia** [comment]
probably related to contract deployment settings
@SebastianJ please comment

**Comment by chainum** [comment]
The interface has been switched over to use MaxUint approvals - so this behavior is expected given the current circumstances. Closing the issue for now. Re-open if you think this is incorrect.
