### ISSUE TITLE
[BUG] [POPS] [Soph] when swapping wallet the recent transaction are not being refreshed/updated 

### ISSUE THREAD

**Issue by sophoah** [harmony-one/swoop-testing#18]
**Site/Domain**
swoop2.pops.one

**Describe the bug**
I was performing test on swoop between two different wallets and all the transaction for each wallet just keep adding into the list.

**To Reproduce**
swap wallet and perform any transaction

**Expected behavior**
at wallet swap, the transaction should be update to reflect only the wallet transaction

**Screenshots**
If applicable, add screenshots to help explain your problem. You can drag and drop images straight into this textbox and they'll be uploaded and embedded automatically by Github!
![image](https://user-images.githubusercontent.com/35721420/97104606-25f97680-16f0-11eb-8c0b-4fb520e6f21f.png)

**Additional context**

**Comment by hypnagonia** [comment]
https://github.com/harmony-one/swoop-interface/commit/7e0abee37177132af10e85a2639121d53228730d

**Comment by chainum** [comment]
Nice work, closing!
