### ISSUE TITLE
[BUG] [POPS] [Soph] Adding new liquidity to existing pools shows shows incorrect data during the addition

### ISSUE THREAD

**Issue by sophoah** [harmony-one/swoop-testing#19]
**Site/Domain**
swoop2.pops.one

**Describe the bug**
there are existing liquidity which i have 100% of the share pool. I am trying to add more liquidity to the same pool. During the creation windows, the share pool doesn't seems to take into consideration the existing liquidity i already have in and instead considered that new liquidity addition as a new one.

**To Reproduce**
Add new liquidity to a pair we previously add liquidity

**Expected behavior**
the share of pool should take into consideration the existing liquidity and show the correct %

**Screenshots**
**during creation :**
![image](https://user-images.githubusercontent.com/35721420/97104864-02cfc680-16f2-11eb-82f0-f6535a35ea2e.png)

![image](https://user-images.githubusercontent.com/35721420/97104869-082d1100-16f2-11eb-8afd-b15d7a83d97d.png)

**end result (which is expected and correct) :**
![image](https://user-images.githubusercontent.com/35721420/97104855-f64b6e00-16f1-11eb-81a3-c3ca5be8190a.png)
![image](https://user-images.githubusercontent.com/35721420/97104894-3d396380-16f2-11eb-9bd6-37ed7a046840.png)

**Additional context**

**Comment by hypnagonia** [comment]
not sure if we need to change this behavior..
the form explicitly shows current supplement amounts, not total
@SebastianJ what do you think?

**Comment by chainum** [comment]
Regular Uniswap works this way as well:
![Screenshot 2020-10-28 at 13 43 51](https://user-images.githubusercontent.com/13743/97437413-b8ce2700-1923-11eb-8448-63545e35d862.png)
![Screenshot 2020-10-28 at 13 43 59](https://user-images.githubusercontent.com/13743/97437424-bbc91780-1923-11eb-9d96-44524ca88e89.png)
![Screenshot 2020-10-28 at 13 44 22](https://user-images.githubusercontent.com/13743/97437435-bec40800-1923-11eb-990d-2ca7202dc0fc.png)
