### ISSUE TITLE
[P-OPS] Approve button gets stuck at Approving.... (during second swap)

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/swoop-testing#2]
First token swap goes through fine, second swap gets stuck at "Approving...." button. Not a show stopper. Refreshing the page allows to proceed. https://streamable.com/sqrvup (Happens both on brave and chrome). To recreate the issue - Pick any pair, Approve, Swap. Reverse the pair. Approve button will now change to "Approving..." and be stuck there. If you refresh the page, button becomes active again

**Comment by chainum** [comment]
Should already have been fixed by @hypnagonia - please re-open if this is not the case.
