### ISSUE TITLE
[BUG] Strange difference between TX and reality (or other way around)!?

### ISSUE THREAD

**Issue by JB273** [harmony-one/swoop-testing#24]
swoop2.pops.one:

![image](https://user-images.githubusercontent.com/54506968/97224363-52d18a80-17d1-11eb-8035-f152476a6c92.png)

Got some weird output when providing liquidity, check the balances... and TX confirmation!?

**Comment by JB273** [comment]
It look like the confirmation display correct when doing 1BUSD --> 1ETH 
But when doing 1ETH --> 1 BUSD it's off, probably because of 1BUSD is worth over 1000ETH?

So might be cosmetic, it displays correct value after doing swap.... just not the confirmation and also not the TX line in the wallet...

**Comment by JB273** [comment]
![image](https://user-images.githubusercontent.com/54506968/97230659-9ed4fd00-17da-11eb-900a-6cf1101ae20e.png)

**Comment by JB273** [comment]
This is still not good:
![image](https://user-images.githubusercontent.com/54506968/97493960-ff447580-1965-11eb-9ca8-c7517aa1b5af.png)
![image](https://user-images.githubusercontent.com/54506968/97494011-11beaf00-1966-11eb-9c04-d91a0fc7e9f6.png)

**Comment by JB273** [comment]
Tried with other account and other browser, caps it at after third character it seems...
![image](https://user-images.githubusercontent.com/54506968/97494561-bccf6880-1966-11eb-80a8-468a7e02cb86.png)

**Comment by JB273** [comment]
Removing Liquidity is the same...
![image](https://user-images.githubusercontent.com/54506968/97494761-0d46c600-1967-11eb-9509-e50298933285.png)

**Comment by chainum** [comment]
@hypnagonia - can you take a look at this and see if it's related to the number formatting somehow?

**Comment by chainum** [comment]
Potentially fixed on a newer verison of Swoop meanwhile this specific outcome might've happened on an older set of testing servers. Closing for now, re-opening if issue can be reproduced on https://swoop.exchange.
