### ISSUE TITLE
[BUG] Unable to remove liquidity! Seems like CORS is back?

### ISSUE THREAD

**Issue by JB273** [harmony-one/swoop-testing#25]
![image](https://user-images.githubusercontent.com/54506968/97238978-e2376780-17ea-11eb-82e6-ed11d67208ff.png)

**Comment by JB273** [comment]
Running this on Microsoft Edge (Chromium based) browser and is on swoop2.pops.one

**Comment by chainum** [comment]
Can you re-test this using Chrome, Firefox or Brave and see if the same thing happens again? CORS configs shouldn't have been changed for the RPC:s, so weird to see this happen again.

**Comment by JB273** [comment]
Ok seems not to be CORS (luckely!)
![image](https://user-images.githubusercontent.com/54506968/97353628-8cb79500-1894-11eb-8ccd-4e0e193133f7.png)

Still on Edge though... seems something with OneWallet...

**Comment by JB273** [comment]
Ok seems to be fixed at all now, seemed the Chrome extension was the wrong version (was version 1.0.5, but still the development edition).
