### ISSUE TITLE
[Minor UI suggestion] Chainlink logo looks disproportionate

### ISSUE THREAD

**Issue by MaggieWang-Harmony** [harmony-one/swoop-testing#26]
![image](https://user-images.githubusercontent.com/55899206/97514951-2e022200-194d-11eb-8eea-1270d67a1e72.png)

Chainlink logo looks a bit disproportionate.

**Comment by chainum** [comment]
I updated the logo to follow the same image width/height as 1ETH, 1BTC etc:
![Screenshot 2020-10-29 at 14 55 05](https://user-images.githubusercontent.com/13743/97583072-cef8e780-19f6-11eb-9e14-f3c87766812e.png)
