### ISSUE TITLE
[BUG] Need to manually refresh the page each time I create a new pool. 

### ISSUE THREAD

**Issue by MaggieWang-Harmony** [harmony-one/swoop-testing#27]
![image](https://user-images.githubusercontent.com/55899206/97622474-913d9400-19e1-11eb-9bca-a2827bf4a436.png)

Need to manually refresh the page each time after I create a new pool, otherwise, it will be a blank page.

**Comment by Dewansahil** [comment]
@hypnagonia

**Comment by hypnagonia** [comment]
@MaggieWang-Harmony 
what was the browser? can you reproduce the problem in incognito mode?

**Comment by MaggieWang-Harmony** [comment]
I can't connect to my wallet using incognito?
