### ISSUE TITLE
[BUG] [P-OPS] [MirrorMirage / Soph] Balance display mismatch 

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/swoop-testing#3]
ONE balance display mismatch. 
![image](https://user-images.githubusercontent.com/29485946/97004475-2d811a00-154e-11eb-9c78-f5be528d5f62.png)

**Comment by chainum** [comment]
Not sure about the status of this - @hypnagonia can you check?

**Comment by chainum** [comment]
Additional info from the Notion page (submitted by Mirror):
![Untitled](https://user-images.githubusercontent.com/13743/97025730-c4eb6a80-1558-11eb-8d97-fae368841b70.png)

**Comment by chainum** [comment]
More info from Soph:
![Untitled](https://user-images.githubusercontent.com/13743/97026197-5f4bae00-1559-11eb-9437-c8f260c9b354.png)

"however correct on the swap page:"

![Untitled](https://user-images.githubusercontent.com/13743/97026251-6f638d80-1559-11eb-9857-e71c5711e191.png)

**Comment by sophoah** [comment]
another rounding issue during the adding 1BUSD/1BTC (1102.34/1000) liquidity workflow
![image](https://user-images.githubusercontent.com/35721420/97089154-7e853100-1668-11eb-8297-c5bd1f9c85fd.png)

**Comment by hypnagonia** [comment]
made rounding for all displayed currencies `toSignificant(6)`
