### ISSUE TITLE
[BUG] [P-OPS] [Yellowsin] Pools not paired with ONE don't automatically show up in the pool liquidity list

### ISSUE THREAD

**Issue by chainum** [harmony-one/swoop-testing#5]
"Pools that dont have a pair with ONE are not added automatically to the pool liquidity list. I had to use the Import it for them to show up. An example for 1BUSD/1ETH. Would be nice that these were added automatically as well (if possible)."

![Untitled](https://user-images.githubusercontent.com/13743/97026577-d719d880-1559-11eb-96cb-f187981d2c74.png)

**Comment by hypnagonia** [comment]
done. current logic adds pair to user's watch list and saves to local storage after user's provided liquidity. 

also watched pairs can be predefined here
https://github.com/harmony-one/swoop-interface/blob/master/src/constants/index.ts#L60

**Comment by chainum** [comment]
Awesome, closing.
