### ISSUE TITLE
[BUG] [P-OPS] [JB] Token icons are missing for some token pairs

### ISSUE THREAD

**Issue by chainum** [harmony-one/swoop-testing#8]
"removing liquidity, couple of things: 1. no icons displayed for tokens (Using Edge browser, chromium based)"

![Untitled](https://user-images.githubusercontent.com/13743/97027823-93c06980-155b-11eb-8a52-de92b35a353b.png)

**Comment by chainum** [comment]
The reason this happens is because of icons being fetched from trustwallet's github repository:

```
const getTokenLogoURL = (address: string) =>
  `https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/${address}/logo.png`
```

That repository doesn't have logos for our custom testing tokens.

We will have to implement some kind of workaround for the mainnet HRC-20 tokens.

**Comment by err0r711** [comment]
![seb1](https://user-images.githubusercontent.com/31262326/97040868-e6efe780-156e-11eb-84c0-a519dc7b4ded.jpg)

same here

**Comment by hypnagonia** [comment]
done, made fallback to https://swoop-exchange.s3-us-west-1.amazonaws.com/tokens/${currency.symbol}.png

**Comment by chainum** [comment]
Fixed:
<img width="512" alt="Screenshot 2020-10-27 at 14 47 14" src="https://user-images.githubusercontent.com/13743/97310291-53b2fc80-1863-11eb-8c9e-fd03437e677d.png">
